---

spring:
  profiles : dev

nexus3:
  url : http://15.114.100.2:8081/service/siesta/rest/v1/script
  username  : admin
  password  : admin123


---

spring:
  profiles : prod

nexus3:
  url : http://127.0.0.1:8081/service/siesta/rest/v1/script
  username  : admin123
  password  : admin123123


